export { 
    SET_ONE_PRODUCT,
    SET_ALL_PRODUCTS,
    SET_POPULAR_PRODUCTS,
    GET_ONE_PRODUCT,
    GET_ALL_PRODUCTS,
    GET_POPULAR_PRODUCTS,

    SET_PRODUCTS_SORT_ASC,
    SET_PRODUCTS_SORT_TYPE,
    SET_PRODUCTS_SORT_PAGE,
    SET_PRODUCTS_FILTER_TYPE,
    SET_PRODUCTS_FILTER_STOCK,

    ADD_PRODUCT_TO_BASKET,
    DELETE_PRODUCT_FROM_BASKET,

    ADD_PRODUCT_TO_FAVORITE,
    DELETE_PRODUCT_FROM_FAVORITE,
}

const SET_ONE_PRODUCT = "SET_ONE_PRODUCT"
const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS"
const SET_POPULAR_PRODUCTS = "SET_POPULAR_PRODUCTS"
const GET_ONE_PRODUCT = "GET_ONE_PRODUCT"
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS" 
const GET_POPULAR_PRODUCTS = "GET_POPULAR_PRODUCTS"

const SET_PRODUCTS_SORT_PAGE = "SET_PRODUCTS_SORT_PAGE" 
const SET_PRODUCTS_SORT_ASC = "SET_PRODUCTS_SORT_ASC"
const SET_PRODUCTS_SORT_TYPE = "SET_PRODUCTS_SORT_TYPE"
const SET_PRODUCTS_FILTER_TYPE = "SET_PRODUCTS_FILTER_TYPE" 
const SET_PRODUCTS_FILTER_STOCK = "SET_PRODUCTS_FILTER_STOCK"

const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET"
const DELETE_PRODUCT_FROM_BASKET = "DELETE_PRODUCT_FROM_BASKET"

const ADD_PRODUCT_TO_FAVORITE = "ADD_PRODUCT_TO_FAVORITE"
const DELETE_PRODUCT_FROM_FAVORITE = "DELETE_PRODUCT_FROM_FAVORITE"